version: "3.8"
services:
  db:
    image: postgres:13-alpine
    container_name: templates_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: templates
    ports:
      - "5432:5432"
