name: Development server deployment

on:
  push:
    branches: ["master"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          username: ${{ secrets.SERVER_USER }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd /home/www/primary-admin-backend
            git checkout -f master
            git pull origin master

            pnpm run typeorm migration:run
            pnpm install --frozen-lockfile
            pnpm run build exit 1
            pm2 reload primary-admin-backend || exit 1
